/**
 * Internal SEO Research Map for Profitivas Calculators.
 *
 * Captures query intent, keyword hierarchies, semantic terminology,
 * editorial headings, FAQ targets, and internal linking structure.
 * Stored internally for architecture and verification without public keyword stuffing.
 */

export interface SeoCalculatorTarget {
  slug: string;
  url: string;
  name: string;
  h1: string;
  title: string;
  metaDescription: string;
  primaryKeyword: string;
  secondaryKeywords: string[];
  semanticTerms: string[];
  searchIntent: string;
  supportingHeadings: string[];
  faqOpportunities: string[];
  relatedCalculators: string[];
}

export const SEO_RESEARCH_MAP: Record<string, SeoCalculatorTarget> = {
  'profit-margin': {
    slug: 'profit-margin-calculator',
    url: 'https://profitivas.com/profit-margin-calculator',
    name: 'Profit Margin Calculator',
    h1: 'Profit Margin Calculator',
    title: 'Profit Margin Calculator — Calculate Profit Margin',
    metaDescription: 'Calculate profit margin percentage, gross profit, and markup from unit cost and revenue, or determine your required selling price from a target margin.',
    primaryKeyword: 'profit margin calculator',
    secondaryKeywords: [
      'profit margin',
      'profit margin formula',
      'how to calculate profit margin',
      'gross profit margin',
      'profit margin percentage',
      'profit margin calculation',
      'calculate profit margin',
    ],
    semanticTerms: [
      'cost',
      'selling price',
      'revenue',
      'gross profit',
      'gross margin',
      'markup',
      'profit percentage',
      'profit per sale',
    ],
    searchIntent: 'User wants to calculate profit margin from cost and selling price, or understand the formula.',
    supportingHeadings: [
      'What is Profit Margin?',
      'How to Calculate Profit Margin',
      'Profit Margin Formula',
      'Profit Margin vs. Markup',
      'Worked Business Example',
      'Frequently Asked Questions',
    ],
    faqOpportunities: [
      'What is profit margin?',
      'How do you calculate profit margin?',
      'What is the difference between margin and markup?',
      'Is gross margin the same as net margin?',
      'How do I calculate selling price from a target margin?',
    ],
    relatedCalculators: [
      'markup-calculator',
      'selling-price-calculator',
      'discount-calculator',
      'gross-profit-calculator',
    ],
  },

  markup: {
    slug: 'markup-calculator',
    url: 'https://profitivas.com/markup-calculator',
    name: 'Markup Calculator',
    h1: 'Markup Calculator',
    title: 'Markup Calculator — Calculate Markup & Selling Price',
    metaDescription: 'Calculate markup percentage, gross profit dollars, and resulting profit margin from unit cost and selling price, or find your target selling price.',
    primaryKeyword: 'markup calculator',
    secondaryKeywords: [
      'markup percentage calculator',
      'markup formula',
      'how to calculate markup',
      'calculate markup',
      'markup vs margin',
      'selling price from markup',
    ],
    semanticTerms: [
      'cost',
      'selling price',
      'profit',
      'markup percentage',
      'profit margin',
      'price increase',
      'cost-plus pricing',
    ],
    searchIntent: 'Calculate markup percentage and required selling price or understand the difference between markup and margin.',
    supportingHeadings: [
      'What is Markup?',
      'How to Calculate Markup',
      'Markup Formula',
      'Markup vs. Margin: Key Differences',
      'Cost-Plus Pricing Example',
      'Frequently Asked Questions',
    ],
    faqOpportunities: [
      'What is the difference between markup and profit margin?',
      'Can markup be higher than 100%?',
      'Why does a 100% markup equal a 50% profit margin?',
      'What is cost-plus pricing?',
      'When is a markup calculator useful?',
    ],
    relatedCalculators: [
      'profit-margin-calculator',
      'selling-price-calculator',
      'discount-calculator',
      'gross-profit-calculator',
    ],
  },

  'selling-price': {
    slug: 'selling-price-calculator',
    url: 'https://profitivas.com/selling-price-calculator',
    name: 'Selling Price Calculator',
    h1: 'Selling Price Calculator',
    title: 'Selling Price Calculator — Find Your Required Selling Price',
    metaDescription: 'Calculate required selling price based on unit cost and desired profit margin or markup. Instant, client-side pricing calculator for retail and ecommerce.',
    primaryKeyword: 'selling price calculator',
    secondaryKeywords: [
      'calculate selling price',
      'selling price formula',
      'how to calculate selling price',
      'product selling price calculator',
      'selling price from cost and margin',
      'selling price from markup',
    ],
    semanticTerms: [
      'cost',
      'target margin',
      'markup',
      'profit',
      'retail price',
      'product pricing',
      'unit economics',
    ],
    searchIntent: 'Determine the exact selling price needed to achieve a target profit margin or markup based on product unit cost.',
    supportingHeadings: [
      'How to Determine Selling Price',
      'Selling Price from Target Margin',
      'Selling Price from Markup',
      'Pricing Comparison: Margin vs. Markup Target',
      'Retail Pricing Worked Example',
      'Frequently Asked Questions',
    ],
    faqOpportunities: [
      'How do you calculate selling price from cost and margin?',
      'Why is selling price from margin different from markup?',
      'Can target margin be 100%?',
      'When should I use markup instead of margin?',
    ],
    relatedCalculators: [
      'profit-margin-calculator',
      'markup-calculator',
      'discount-calculator',
      'gross-profit-calculator',
    ],
  },

  discount: {
    slug: 'discount-calculator',
    url: 'https://profitivas.com/discount-calculator',
    name: 'Discount Calculator',
    h1: 'Discount Calculator',
    title: 'Discount Calculator — Calculate Sale Price & Savings',
    metaDescription: 'Calculate final sale prices, dollar savings, and percentage discounts instantly for retail, ecommerce, and seasonal promotions.',
    primaryKeyword: 'discount calculator',
    secondaryKeywords: [
      'discount percentage calculator',
      'sale price calculator',
      'percent off calculator',
      'discount price calculator',
      'calculate discount',
      'price after discount',
      'how to calculate discount',
    ],
    semanticTerms: [
      'original price',
      'sale price',
      'amount saved',
      'percentage off',
      'markdown',
      'discount rate',
    ],
    searchIntent: 'Calculate discounted sale price and savings amount from an original price and percentage discount, or reverse calculate the discount rate.',
    supportingHeadings: [
      'How Discounts Work',
      'Discount and Sale Price Formulas',
      'Reverse Markdown Calculation',
      'Retail Promotion Worked Example',
      'Frequently Asked Questions',
    ],
    faqOpportunities: [
      'How do I calculate price after discount?',
      'How do you calculate a discount percentage?',
      'How do you calculate what percentage was discounted?',
      'Can discount exceed 100%?',
    ],
    relatedCalculators: [
      'selling-price-calculator',
      'profit-margin-calculator',
      'markup-calculator',
      'gross-profit-calculator',
    ],
  },

  'gross-profit': {
    slug: 'gross-profit-calculator',
    url: 'https://profitivas.com/gross-profit-calculator',
    name: 'Gross Profit Calculator',
    h1: 'Gross Profit Calculator',
    title: 'Gross Profit Calculator — Calculate Gross Profit & Margin',
    metaDescription: 'Calculate gross profit and gross margin from total revenue and cost of goods sold (COGS). Fast, client-side business metrics.',
    primaryKeyword: 'gross profit calculator',
    secondaryKeywords: [
      'gross profit margin calculator',
      'gross profit formula',
      'gross margin calculator',
      'calculate gross profit',
      'gross profit percentage',
    ],
    semanticTerms: [
      'revenue',
      'COGS',
      'cost of goods sold',
      'gross profit',
      'gross margin',
      'sales',
      'direct costs',
    ],
    searchIntent: 'Calculate gross profit dollars and gross margin percentage from total revenue and cost of goods sold (COGS).',
    supportingHeadings: [
      'What is Gross Profit?',
      'How to Calculate Gross Profit',
      'Gross Profit vs. Gross Margin',
      'COGS Accounting Principles',
      'E-Commerce Worked Example',
      'Frequently Asked Questions',
    ],
    faqOpportunities: [
      'How do I calculate gross profit?',
      'What is the difference between gross profit and net profit?',
      'What is a healthy gross profit margin?',
      'Does COGS include advertising spend?',
    ],
    relatedCalculators: [
      'profit-margin-calculator',
      'break-even-calculator',
      'target-profit-calculator',
      'revenue-calculator',
    ],
  },

  'break-even': {
    slug: 'break-even-calculator',
    url: 'https://profitivas.com/break-even-calculator',
    name: 'Break-Even Calculator',
    h1: 'Break-Even Calculator',
    title: 'Break-Even Calculator — Find Your Break-Even Point',
    metaDescription: 'Find your break-even point in units and sales dollars using fixed overhead, unit price, and variable costs. Free business calculator.',
    primaryKeyword: 'break even calculator',
    secondaryKeywords: [
      'break even point calculator',
      'break even analysis',
      'break even formula',
      'break even sales calculator',
      'break even units',
      'calculate break even point',
    ],
    semanticTerms: [
      'fixed costs',
      'variable costs',
      'selling price',
      'contribution margin',
      'break-even units',
      'break-even revenue',
    ],
    searchIntent: 'Find the sales volume in units and dollars required to cover all fixed and variable costs with zero operating profit/loss.',
    supportingHeadings: [
      'What is the Break-Even Point?',
      'Contribution Margin Explained',
      'Break-Even Formulas (Units & Revenue)',
      'Why Unit Price Must Exceed Variable Cost',
      'Worked Business Example',
      'Frequently Asked Questions',
    ],
    faqOpportunities: [
      'How do I calculate break-even units?',
      'What happens if variable cost exceeds selling price?',
      'What is contribution margin ratio?',
    ],
    relatedCalculators: [
      'target-profit-calculator',
      'gross-profit-calculator',
      'revenue-calculator',
      'profit-margin-calculator',
    ],
  },

  'target-profit': {
    slug: 'target-profit-calculator',
    url: 'https://profitivas.com/target-profit-calculator',
    name: 'Target Profit Calculator',
    h1: 'Target Profit Calculator',
    title: 'Target Profit Calculator — Calculate Required Sales',
    metaDescription: 'Calculate units and revenue needed to hit your target business profit. Plan sales goals based on fixed overhead and unit margins.',
    primaryKeyword: 'target profit calculator',
    secondaryKeywords: [
      'target profit formula',
      'required sales calculator',
      'units needed for target profit',
      'sales volume for target profit',
      'profit target calculator',
    ],
    semanticTerms: [
      'fixed costs',
      'variable costs',
      'selling price',
      'contribution margin',
      'required units',
      'target operating profit',
    ],
    searchIntent: 'Determine units and gross revenue needed to hit a specific dollar operating profit after covering all fixed overhead.',
    supportingHeadings: [
      'Target Profit vs. Break-Even Analysis',
      'Target Profit Formula',
      'Contribution Margin Dynamics',
      'Planning Sales Goals Worked Example',
      'Frequently Asked Questions',
    ],
    faqOpportunities: [
      'How do I calculate target profit?',
      'How does target profit relate to break-even?',
      'How do I calculate for after-tax target profit?',
    ],
    relatedCalculators: [
      'break-even-calculator',
      'gross-profit-calculator',
      'revenue-calculator',
      'profit-margin-calculator',
    ],
  },

  revenue: {
    slug: 'revenue-calculator',
    url: 'https://profitivas.com/revenue-calculator',
    name: 'Revenue Calculator',
    h1: 'Revenue Calculator',
    title: 'Revenue Calculator — Calculate Total Revenue',
    metaDescription: 'Calculate total sales turnover from unit sales volume and average price per unit. Fast, client-side business forecasting.',
    primaryKeyword: 'revenue calculator',
    secondaryKeywords: [
      'sales revenue calculator',
      'revenue formula',
      'calculate revenue',
      'total revenue calculator',
      'sales calculator',
    ],
    semanticTerms: [
      'units sold',
      'price per unit',
      'sales volume',
      'total sales',
      'revenue per unit',
      'top-line turnover',
    ],
    searchIntent: 'Calculate total sales turnover from unit sales volume and average price per unit.',
    supportingHeadings: [
      'Understanding Total Revenue',
      'Revenue Formula',
      'Revenue vs. Profit Explained',
      'Sales Forecasting Example',
      'Frequently Asked Questions',
    ],
    faqOpportunities: [
      'How do I calculate revenue?',
      'What is the difference between revenue and profit?',
      'What is Average Revenue Per User (ARPU)?',
    ],
    relatedCalculators: [
      'gross-profit-calculator',
      'break-even-calculator',
      'target-profit-calculator',
      'commission-calculator',
    ],
  },

  commission: {
    slug: 'commission-calculator',
    url: 'https://profitivas.com/commission-calculator',
    name: 'Commission Calculator',
    h1: 'Commission Calculator',
    title: 'Commission Calculator — Calculate Sales Commission',
    metaDescription: 'Calculate sales commission payouts and total earnings based on transaction volume, percentage rates, and optional base salary.',
    primaryKeyword: 'commission calculator',
    secondaryKeywords: [
      'sales commission calculator',
      'commission percentage calculator',
      'commission rate calculator',
      'calculate sales commission',
      'commission earnings calculator',
    ],
    semanticTerms: [
      'sales',
      'commission rate',
      'commission earned',
      'salesperson',
      'commission payout',
      'sales income',
      'base salary',
    ],
    searchIntent: 'Calculate commission payout and total earnings from closed sales volume and agreed commission percentage rate.',
    supportingHeadings: [
      'How Commission Payouts Work',
      'Commission Formula',
      'Base Salary plus Commission Integration',
      'Commercial Sales Deal Example',
      'Frequently Asked Questions',
    ],
    faqOpportunities: [
      'How is sales commission calculated?',
      'What is a typical sales commission rate?',
      'What is an OTE (On-Target Earnings)?',
    ],
    relatedCalculators: [
      'revenue-calculator',
      'gross-profit-calculator',
      'profit-margin-calculator',
      'selling-price-calculator',
    ],
  },

  roi: {
    slug: 'roi-calculator',
    url: 'https://profitivas.com/roi-calculator',
    name: 'ROI Calculator',
    h1: 'ROI Calculator',
    title: 'ROI Calculator — Calculate Return on Investment',
    metaDescription: 'Calculate return on investment (ROI) percentage, net profit, and investment multiple. Fast, client-side business metrics.',
    primaryKeyword: 'ROI calculator',
    secondaryKeywords: [
      'return on investment calculator',
      'ROI formula',
      'calculate ROI',
      'investment return calculator',
      'ROI percentage calculator',
    ],
    semanticTerms: [
      'initial investment',
      'final value',
      'profit',
      'return',
      'investment gain',
      'ROI percentage',
      'multiple',
    ],
    searchIntent: 'Evaluate return on investment percentage, net dollar gain, and return multiple from invested capital and final return.',
    supportingHeadings: [
      'What is Return on Investment (ROI)?',
      'How to Calculate ROI',
      'ROI Formula & Capital Multiples',
      'ROI vs. ROAS Explained',
      'Marketing Campaign Investment Example',
      'Frequently Asked Questions',
    ],
    faqOpportunities: [
      'How is ROI calculated?',
      'What is a good ROI for a business?',
      'How is ROI different from ROAS?',
    ],
    relatedCalculators: [
      'roas-calculator',
      'cac-calculator',
      'conversion-rate-calculator',
      'gross-profit-calculator',
    ],
  },

  roas: {
    slug: 'roas-calculator',
    url: 'https://profitivas.com/roas-calculator',
    name: 'ROAS Calculator',
    h1: 'ROAS Calculator',
    title: 'ROAS Calculator — Calculate Return on Ad Spend',
    metaDescription: 'Calculate return on ad spend (ROAS) multiple and percentage from advertising budget and attributed revenue. Free marketing tool.',
    primaryKeyword: 'ROAS calculator',
    secondaryKeywords: [
      'return on ad spend calculator',
      'ROAS formula',
      'calculate ROAS',
      'advertising ROI',
      'ad spend calculator',
      'ROAS ratio',
    ],
    semanticTerms: [
      'advertising spend',
      'ad revenue',
      'campaign revenue',
      'paid advertising',
      'return on ad spend',
      'ROAS multiple',
      'ACoS',
    ],
    searchIntent: 'Calculate return on ad spend multiple and percentage from advertising budget and attributed sales revenue.',
    supportingHeadings: [
      'What is Return on Ad Spend (ROAS)?',
      'How to Calculate ROAS',
      'ROAS Multiple vs. ROAS Percentage',
      'ROAS vs. ROI: Key Differences',
      'Break-Even ROAS Calculation',
      'Paid Campaign Worked Example (5.00x Target)',
      'Frequently Asked Questions',
    ],
    faqOpportunities: [
      'What is ROAS and how is it calculated?',
      'How is ROAS different from ROI?',
      'What is a good ROAS?',
      'What is break-even ROAS?',
    ],
    relatedCalculators: [
      'roi-calculator',
      'cac-calculator',
      'conversion-rate-calculator',
      'revenue-calculator',
    ],
  },

  cac: {
    slug: 'cac-calculator',
    url: 'https://profitivas.com/cac-calculator',
    name: 'CAC Calculator',
    h1: 'CAC Calculator',
    title: 'CAC Calculator — Calculate Customer Acquisition Cost',
    metaDescription: 'Calculate customer acquisition cost (CAC) from total sales and marketing spend divided by new customers acquired.',
    primaryKeyword: 'CAC calculator',
    secondaryKeywords: [
      'customer acquisition cost calculator',
      'customer acquisition cost',
      'CAC formula',
      'calculate CAC',
      'cost to acquire a customer',
      'customer acquisition cost formula',
    ],
    semanticTerms: [
      'sales and marketing spend',
      'new customers',
      'acquisition cost',
      'customer acquisition',
      'unit economics',
      'blended CAC',
      'paid CAC',
    ],
    searchIntent: 'Calculate the average blended cost to acquire a single paying customer from marketing spend and customer acquisitions.',
    supportingHeadings: [
      'What is Customer Acquisition Cost (CAC)?',
      'How to Calculate CAC',
      'Fully Loaded vs. Paid CAC',
      'SaaS Acquisition Worked Example',
      'Frequently Asked Questions',
    ],
    faqOpportunities: [
      'How is CAC calculated?',
      'What is a good Customer Acquisition Cost (CAC)?',
      'What is the difference between blended CAC and paid CAC?',
    ],
    relatedCalculators: [
      'ltv-calculator',
      'ltv-cac-calculator',
      'roas-calculator',
      'conversion-rate-calculator',
    ],
  },

  ltv: {
    slug: 'ltv-calculator',
    url: 'https://profitivas.com/ltv-calculator',
    name: 'LTV Calculator',
    h1: 'LTV Calculator',
    title: 'LTV Calculator — Estimate Customer Lifetime Value',
    metaDescription: 'Calculate customer lifetime value (LTV / CLV) based on order value, purchase frequency, and retention lifespan.',
    primaryKeyword: 'LTV calculator',
    secondaryKeywords: [
      'customer lifetime value calculator',
      'CLV calculator',
      'customer lifetime value',
      'LTV formula',
      'calculate customer lifetime value',
    ],
    semanticTerms: [
      'average purchase value',
      'purchase frequency',
      'customer lifespan',
      'customer value',
      'lifetime revenue',
      'customer economics',
      'churn rate',
    ],
    searchIntent: 'Estimate customer lifetime value (LTV / CLV) from average order value, purchase frequency, and retention lifespan.',
    supportingHeadings: [
      'What is Customer Lifetime Value (LTV)?',
      'Simple LTV Estimation Methodology',
      'Revenue LTV vs. Gross Margin LTV',
      'Subscription & Retention Worked Example',
      'Frequently Asked Questions',
    ],
    faqOpportunities: [
      'How is LTV calculated?',
      'How do you calculate customer lifespan from churn rate?',
      'Why is LTV important for customer acquisition?',
    ],
    relatedCalculators: [
      'cac-calculator',
      'ltv-cac-calculator',
      'revenue-calculator',
      'conversion-rate-calculator',
    ],
  },

  'ltv-cac': {
    slug: 'ltv-cac-calculator',
    url: 'https://profitivas.com/ltv-cac-calculator',
    name: 'LTV:CAC Calculator',
    h1: 'LTV:CAC Calculator',
    title: 'LTV:CAC Calculator — Compare LTV & Customer Acquisition Cost',
    metaDescription: 'Calculate your LTV:CAC ratio to evaluate customer acquisition efficiency, payback feasibility, and long-term business sustainability.',
    primaryKeyword: 'LTV CAC calculator',
    secondaryKeywords: [
      'LTV:CAC ratio calculator',
      'LTV to CAC calculator',
      'LTV CAC ratio',
      'customer lifetime value to CAC',
      'LTV CAC formula',
    ],
    semanticTerms: [
      'customer lifetime value',
      'customer acquisition cost',
      'unit economics',
      'customer economics',
      'acquisition efficiency',
      'payback period',
      'ratio',
    ],
    searchIntent: 'Compare Customer Lifetime Value to Customer Acquisition Cost to benchmark growth efficiency and unit economics health.',
    supportingHeadings: [
      'What is the LTV:CAC Ratio?',
      'How to Calculate LTV:CAC',
      'Interpreting Benchmark Ratios (Why Context Matters)',
      'SaaS Unit Economics Example ($600 LTV / $200 CAC = 3.00:1)',
      'Frequently Asked Questions',
    ],
    faqOpportunities: [
      'What does LTV:CAC mean?',
      'What is a good LTV:CAC ratio?',
      'What is CAC Payback Period?',
    ],
    relatedCalculators: [
      'ltv-calculator',
      'cac-calculator',
      'roas-calculator',
      'break-even-calculator',
    ],
  },

  'conversion-rate': {
    slug: 'conversion-rate-calculator',
    url: 'https://profitivas.com/conversion-rate-calculator',
    name: 'Conversion Rate Calculator',
    h1: 'Conversion Rate Calculator',
    title: 'Conversion Rate Calculator — Calculate Conversion Rate',
    metaDescription: 'Calculate conversion rate percentages and drop-off counts from sessions and conversions. Free funnel optimization calculator.',
    primaryKeyword: 'conversion rate calculator',
    secondaryKeywords: [
      'conversion rate formula',
      'calculate conversion rate',
      'conversion percentage calculator',
      'conversion rate calculation',
      'CVR calculator',
    ],
    semanticTerms: [
      'conversions',
      'visitors',
      'leads',
      'customers',
      'traffic',
      'conversion percentage',
      'drop-off rate',
      'funnel',
    ],
    searchIntent: 'Calculate conversion rate percentage and drop-off rate from visitors and completed conversions.',
    supportingHeadings: [
      'What is Conversion Rate?',
      'How to Calculate Conversion Rate',
      'Funnel Drop-Off Rate Analysis',
      'Checkout Funnel Worked Example',
      'Frequently Asked Questions',
    ],
    faqOpportunities: [
      'How is conversion rate calculated?',
      'What is a typical ecommerce conversion rate?',
      'How do small conversion rate gains impact CAC?',
    ],
    relatedCalculators: [
      'roas-calculator',
      'cac-calculator',
      'roi-calculator',
      'revenue-calculator',
    ],
  },
};
