import type { CalculatorContent } from '../types';

export const roiContent: CalculatorContent = {
  meta: {
    id: 'roi',
    slug: 'roi-calculator',
    name: 'ROI Calculator',
    shortName: 'ROI',
    category: 'business',
    status: 'active',
    tagline: 'Calculate return on investment percentage and net profit gain.',
    description: 'Evaluate the profitability and efficiency of business investments, capital projects, or marketing campaigns.',
    seoTitle: 'ROI Calculator — Calculate Return on Investment',
    seoDescription: 'Calculate return on investment (ROI) percentage, net profit, and investment multiple. Fast, client-side business metrics.',
    featured: true,
  },
  formulas: [
    {
      title: 'Net Profit ($)',
      formula: 'Net Profit = Final Return - Initial Investment',
      plainText: 'Subtract invested capital from total cash returned.',
      explanation: 'The actual dollar earnings generated by the investment.',
    },
    {
      title: 'Return on Investment (ROI %)',
      formula: 'ROI (%) = (Net Profit ÷ Initial Investment) × 100',
      plainText: 'Divide net profit by initial investment, then multiply by 100.',
      explanation: 'Percentage return relative to the original capital committed.',
    },
    {
      title: 'Investment Multiple',
      formula: 'Multiple = Final Return ÷ Initial Investment',
      plainText: 'Divide final return by initial investment.',
      explanation: 'The factor by which invested capital grew.',
    },
  ],
  workedExample: {
    title: 'Marketing Campaign ROI ($5k Investment / $8.5k Return)',
    scenario: 'A company invests $5,000.00 into a growth initiative, generating $8,500.00 in attributed return.',
    inputs: {
      'Initial Investment': '$5,000.00',
      'Total Return': '$8,500.00',
    },
    steps: [
      'Net Profit = $8,500.00 - $5,000.00 = $3,500.00',
      'ROI (%) = ($3,500.00 ÷ $5,000.00) × 100 = 70.00%',
      'Multiple = $8,500.00 ÷ $5,000.00 = 1.70x',
    ],
    results: {
      'Net Profit': '$3,500.00',
      'ROI Percentage': '70.00%',
      'Return Multiple': '1.70x',
    },
    takeaway: 'The investment yielded a 70.00% net return, turning every $1.00 of capital into $1.70.',
  },
  assumptions: [
    {
      term: 'Direct Attribution',
      definition: 'Assumes the return revenue is directly and accurately attributable to the initial investment.',
    },
    {
      term: 'Single Time Period',
      definition: 'Calculates nominal return without adjusting for inflation or multi-year discounted cash flow.',
    },
  ],
  faqs: [
    {
      question: 'How is ROI calculated?',
      answer:
        'ROI is calculated by subtracting initial investment from final return to find net profit, dividing that profit by the initial investment, and multiplying by 100: ROI (%) = ((Return - Investment) ÷ Investment) × 100.',
    },
    {
      question: 'What is a good ROI for a business?',
      answer: 'Standard long-term benchmarks range from 10%–15% annually. For short-term marketing initiatives, campaigns often target 30%–70%+ depending on product gross margin.',
    },
    {
      question: 'How is ROI different from ROAS?',
      answer: 'ROAS measures top-line revenue divided by ad spend. ROI measures net profit after subtracting investment costs.',
    },
  ],
  relatedSlugs: [
    'roas-calculator',
    'cac-calculator',
    'conversion-rate-calculator',
    'gross-profit-calculator',
  ],
};
