import type { CalculatorContent } from '../types';

export const ltvContent: CalculatorContent = {
  meta: {
    id: 'ltv',
    slug: 'ltv-calculator',
    name: 'LTV Calculator',
    shortName: 'LTV',
    category: 'marketing',
    status: 'active',
    tagline: 'Calculate customer lifetime value and retention revenue.',
    description: 'Estimate total gross revenue or profit a customer generates throughout their entire relationship with your business.',
    seoTitle: 'LTV Calculator — Estimate Customer Lifetime Value',
    seoDescription: 'Calculate customer lifetime value (LTV / CLV) based on order value, purchase frequency, and retention lifespan.',
    featured: true,
  },
  formulas: [
    {
      title: 'Customer Lifetime Value ($)',
      formula: 'LTV = Average Order Value × Purchase Frequency × Customer Lifespan',
      plainText: 'Multiply average purchase value by annual purchase frequency, then multiply by lifespan in years.',
      explanation: 'Projects total top-line revenue generated by an average customer account before churn.',
    },
    {
      title: 'Annual Customer Value ($)',
      formula: 'Annual Value = Average Order Value × Purchase Frequency',
      plainText: 'Multiply average order value by annual purchase frequency.',
      explanation: 'The expected yearly revenue generated per active customer.',
    },
  ],
  workedExample: {
    title: 'Subscription Brand Lifetime Value ($60 AOV / 4x Frequency / 3 Yrs)',
    scenario: 'A direct-to-consumer brand records an average order value of $60.00, an average repurchase rate of 4 times per year, and an average retention lifespan of 3 years.',
    inputs: {
      'Average Purchase Value': '$60.00',
      'Annual Frequency': '4 purchases/yr',
      'Customer Lifespan': '3 years',
    },
    steps: [
      'Annual Customer Value = $60.00 × 4 = $240.00 per year',
      'Lifetime Purchases = 4 × 3 = 12 orders',
      'Customer Lifetime Value = $240.00 × 3 = $720.00',
    ],
    results: {
      'Customer Lifetime Value': '$720.00',
      'Annual Value': '$240.00',
      'Total Transactions': '12 orders',
    },
    takeaway: 'Each acquired customer generates an expected $720.00 in cumulative lifetime turnover.',
  },
  assumptions: [
    {
      term: 'Revenue LTV',
      definition: 'Measures gross customer revenue turnover. To calculate gross margin LTV, multiply result by gross margin percentage.',
    },
    {
      term: 'Constant Repurchase Cadence',
      definition: 'Assumes purchase frequency remains consistent across the customer lifespan.',
    },
  ],
  faqs: [
    {
      question: 'How is LTV calculated?',
      answer:
        'Customer Lifetime Value (LTV) is estimated by multiplying average purchase value by annual purchase frequency and customer lifespan in years: LTV = Average Order Value × Purchase Frequency × Customer Lifespan. To calculate gross margin LTV, multiply the result by your gross profit margin percentage.',
    },
    {
      question: 'How do you calculate customer lifespan from churn rate?',
      answer: 'Average customer lifespan equals 1 ÷ Annual Churn Rate. For example, a 25% annual churn rate implies an average lifespan of 1 ÷ 0.25 = 4 years.',
    },
    {
      question: 'Why is LTV important for customer acquisition?',
      answer: 'LTV dictates the upper limit of how much capital you can afford to spend acquiring customers (CAC) while remaining profitable.',
    },
  ],
  relatedSlugs: [
    'cac-calculator',
    'ltv-cac-calculator',
    'revenue-calculator',
    'conversion-rate-calculator',
  ],
};
