import type { CalculatorContent } from '../types';

export const ltvCacContent: CalculatorContent = {
  meta: {
    id: 'ltv-cac',
    slug: 'ltv-cac-calculator',
    name: 'LTV:CAC Calculator',
    shortName: 'LTV:CAC',
    category: 'marketing',
    status: 'active',
    tagline: 'Assess unit economics sustainability and growth efficiency.',
    description: 'Benchmark your customer lifetime value against customer acquisition cost to evaluate marketing efficiency and growth sustainability.',
    seoTitle: 'LTV:CAC Calculator — Compare LTV & Customer Acquisition Cost',
    seoDescription: 'Calculate your LTV:CAC ratio to evaluate customer acquisition efficiency, payback feasibility, and long-term business sustainability.',
    featured: true,
  },
  formulas: [
    {
      title: 'LTV to CAC Ratio',
      formula: 'LTV:CAC Ratio = Customer Lifetime Value ÷ Customer Acquisition Cost',
      plainText: 'Divide Customer Lifetime Value by Customer Acquisition Cost.',
      explanation: 'Calculates how many dollars of customer value are generated for each dollar spent winning new accounts.',
    },
    {
      title: 'Net Value per Customer ($)',
      formula: 'Net Value = Customer Lifetime Value - Customer Acquisition Cost',
      plainText: 'Subtract CAC from LTV.',
      explanation: 'Surplus customer value remaining after fully recovering acquisition marketing spend.',
    },
  ],
  workedExample: {
    title: 'SaaS Unit Economics Benchmark ($600 LTV / $200 CAC)',
    scenario: 'A subscription business projects a Customer Lifetime Value of $600.00 with an average customer acquisition cost of $200.00.',
    inputs: {
      'Customer Lifetime Value': '$600.00',
      'Customer Acquisition Cost': '$200.00',
    },
    steps: [
      'LTV:CAC Ratio = $600.00 ÷ $200.00 = 3.00:1',
      'Net Value per Customer = $600.00 - $200.00 = $400.00',
      'CAC Share of LTV = ($200.00 ÷ $600.00) × 100 = 33.33%',
    ],
    results: {
      'LTV:CAC Ratio': '3.00:1',
      'Net Value': '$400.00',
      'Economic Status': 'Healthy (Target growth benchmark)',
    },
    takeaway: 'Every $1.00 spent on acquisition delivers $3.00 in customer lifetime value, satisfying the classic 3:1 sustainability rule of thumb.',
  },
  assumptions: [
    {
      term: 'Gross vs Margin LTV',
      definition: 'For optimal rigor, compare gross margin LTV against fully blended acquisition cost.',
    },
    {
      term: 'Fully Loaded CAC',
      definition: 'Assumes CAC includes media costs, agency fees, sales commissions, and software tools.',
    },
  ],
  faqs: [
    {
      question: 'What does LTV:CAC mean?',
      answer:
        'LTV:CAC is a core unit economics metric comparing the total lifetime value generated by a customer against the cost required to acquire them: LTV:CAC = LTV ÷ CAC. It indicates whether customer revenue adequately repays acquisition marketing and supports business growth.',
    },
    {
      question: 'What is a good LTV:CAC ratio?',
      answer:
        'While 3.0:1 is commonly cited as a healthy benchmark, context matters significantly. High-margin SaaS companies often target 3:1 to 4:1. Lower ratios (e.g., 2:1) can be viable if cash payback occurs within a few weeks, while higher ratios (e.g., 5:1+) may signal under-investment in growth.',
    },
    {
      question: 'What is CAC Payback Period?',
      answer: 'CAC payback period is the time (in months) it takes a customer to generate enough gross margin to repay their acquisition cost. Top SaaS companies target payback periods under 12 months.',
    },
  ],
  relatedSlugs: [
    'ltv-calculator',
    'cac-calculator',
    'roas-calculator',
    'break-even-calculator',
  ],
};
